apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-server
spec:
  replicas: 3 # 觀察設定
  template:
    metadata:
      labels:
        app: hello-server
    spec:
      containers:
        - name: hello-server
          image: gcr.io/google-samples/hello-app:1.0
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-server
spec:
  selector:
    app: hello-server
  ports:
  - port: 8080
  type: LoadBalancer # ClusterIP, NodePort, LoadBalancer, ExternalName
